### ISSUE TITLE
Cannot import name generic

### ISSUE THREAD

**Issue by urjan** [theatlantic/django-south#2]
Hi,
I'm trying to deploy a django app. MY django version is 1.9.10 and I'm getting an error beacuse one of the scripts in the south library uses 'generic'. I'm not sure how to procedd with it and below is my error log. Please help!

> [Sat Oct 22 15:16:25.464782 2016] [wsgi:warn] [pid 4628:tid 140265021044608] mod_wsgi: Compiled for Python/2.7.11.
> [Sat Oct 22 15:16:25.464841 2016] [wsgi:warn] [pid 4628:tid 140265021044608] mod_wsgi: Runtime using Python/2.7.12.
> [Sat Oct 22 15:16:25.466405 2016] [mpm_event:notice] [pid 4628:tid 140265021044608] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
> [Sat Oct 22 15:16:25.466495 2016] [core:notice] [pid 4628:tid 140265021044608] AH00094: Command line: '/usr/sbin/apache2'
> [Sat Oct 22 11:16:30.667924 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381] mod_wsgi (pid=8544): Target WSGI script '/home/urja/arcana-apt/arcana/wsgi.py' cannot be loaded as Python module.
> [Sat Oct 22 11:16:30.667996 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381] mod_wsgi (pid=8544): Exception occurred processing WSGI script '/home/urja/arcana-apt/arcana/wsgi.py'.
> [Sat Oct 22 11:16:30.668037 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381] Traceback (most recent call last):
> [Sat Oct 22 11:16:30.668077 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]   File "/home/urja/arcana-apt/arcana/wsgi.py", line 59, in <module>
> [Sat Oct 22 11:16:30.668205 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]     application = get_wsgi_application()
> [Sat Oct 22 11:16:30.668233 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]   File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
> [Sat Oct 22 11:16:30.668322 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]     django.setup()
> [Sat Oct 22 11:16:30.668350 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]   File "/usr/local/lib/python2.7/dist-packages/django/**init**.py", line 18, in setup
> [Sat Oct 22 11:16:30.668431 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]     apps.populate(settings.INSTALLED_APPS)
> [Sat Oct 22 11:16:30.668463 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
> [Sat Oct 22 11:16:30.668714 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]     app_config.import_models(all_models)
> [Sat Oct 22 11:16:30.668742 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
> [Sat Oct 22 11:16:30.668904 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]     self.models_module = import_module(models_module_name)
> [Sat Oct 22 11:16:30.668930 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]   File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
> [Sat Oct 22 11:16:30.669011 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]     **import**(name)
> [Sat Oct 22 11:16:30.669035 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]   File "/home/urja/arcana-apt/base/models.py", line 4, in <module>
> [Sat Oct 22 11:16:30.669953 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]     from mptt.models import MPTTModel, TreeForeignKey
> [Sat Oct 22 11:16:30.669982 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]   File "/usr/local/lib/python2.7/dist-packages/mptt/models.py", line 14, in <module>
> [Sat Oct 22 11:16:30.670481 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]     from mptt.fields import TreeForeignKey, TreeOneToOneField, TreeManyToManyField
> [Sat Oct 22 11:16:30.670512 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]   File "/usr/local/lib/python2.7/dist-packages/mptt/fields.py", line 44, in <module>
> [Sat Oct 22 11:16:30.670603 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]     from south.modelsinspector import add_introspection_rules
> [Sat Oct 22 11:16:30.670648 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]   File "/usr/local/lib/python2.7/dist-packages/south/modelsinspector.py", line 20, in <module>
> [Sat Oct 22 11:16:30.670878 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381]     from django.contrib.contenttypes import generic
> [Sat Oct 22 11:16:30.670930 2016] [wsgi:error] [pid 8544:tid 140264748304128] [client 73.30.181.124:51381] ImportError: cannot import name generic

**Comment by fdintino** [comment]
You should not be using django-south with Django 1.9. As you probably know, Django has built-in support for migrations since 1.8.
